function [vehicleTracks] = initializeVehicleTracks()
	vehicleTracks = struct(...
		'id', {}, ...
		'bbox', {}, ...
		'kalman', {}, ...
		'age', {}, ...
		'image', {}, ...
		'visibleCount', {}, ...
		'invisibleCount', {}, ...
		'features', {}, ...
		'class', {}, ...
		'type', {}, ...
		'dimensions', {} ...
		);
end