BasePath = strcat(fileparts(fileparts(mfilename('fullpath'))),'\');
Sept_7 = 'G:\Thesis\Sept 7\';
PPaths = struct (...
	'Base', BasePath, ...
	'Codes', strcat(BasePath, 'Codes\'), ...
	'HaarCodes', strcat(BasePath, 'Codes\Haar Codes\'), ...
    'Detectors', strcat(BasePath, 'Codes\Haar Codes\Detector XML Files\'), ...
    'Classifiers', strcat(BasePath, 'Codes\Classification\Classifier MATs\'), ...
    'Detection', strcat(BasePath, 'Codes\Detection and Count\'), ...
    'BGS', strcat(BasePath, 'Codes\Detection and Count\Background Subtraction\'), ...
    'Classification', strcat(BasePath, 'Codes\Classification\'), ...
    'Positives', strcat(BasePath, 'Codes\Haar Codes\Positive Images Data Structures\'), ...
	'BlobExtractorCodes', strcat(BasePath, 'Codes\BlobExtractorCodes\'), ...
	'TI', strcat(BasePath, 'Codes\Training Images\') ...
	);