function [detectionTracks, nextId] = createNewDetectionTracks(detectionTracks, nextId, unassignedDetections, frame, centroids, bboxes, kConfig)
	centroids = centroids(unassignedDetections, :);
	bboxes = bboxes(unassignedDetections, :);
	
	for i = 1:size(centroids, 1)
		centroid = centroids(i, :);
		bbox = bboxes(i, :);
		
		kalman = configureKalmanFilter(...
			kConfig.MotionModel, ...
			centroid, ...
			kConfig.Error, ...
			kConfig.MotionNoise, ...
			kConfig.MeasurementNoise ...
			);
		
		features = 'Place Holder';
		class = 'Place Holder';
		
		detectionTrack = struct(...
			'id', 	nextId, ...
			'bbox', bbox, ...
			'kalman', kalman, ...
			'age', 1, ...
			'visibleCount', 1, ...
			'invisibleCount', 0, ...
			'features', features, ...
			'class', class ...
			)
		
		detectionTracks(end + 1) = detectionTrack;
		nextId = nextId + 1;
	end
end