function [detectionTracks] = initializeDetectionTracks()
	detectionTracks = struct(...
		'id', {}, ...
		'bbox', {}, ...
		'kalman', {}, ...
		'age', {}, ...
		'visibleCount', {}, ...
		'invisibleCount', {}, ...
		'features', {}, ...
		'class', {} ...
		);
end